### ISSUE TITLE
Click run tool produces error

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-reports-plus#3]
Click on Run Tool and get an error!

Can't locate object method "tool_step1" via package "Koha::Plugin::Com::ByWaterSolutions::KitchenSink" at /home/joy/koha-dev/var/lib/plugins/Koha/Plugin/Com/ByWaterSolutions/KitchenSink.pm line 83.v

**Comment by kidclamp** [comment]
Fixed:
tool options removed
