### ISSUE TITLE
Report number goes negative

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-reports-plus#4]
When selecting a report number with the arrows, the numbers go up....and the numbers go down into the negatives.

When running a negative number report (or a report that doesn't exist) the tool just produces a blank page. 

Request:
Fix the report number entry field?  check on validity of report number?
Display a message if report is not found?

**Comment by kidclamp** [comment]
Fixed:
input field forced to be positive
page reloads if report id invalid
