### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-reports-plus#5]
Can you verify that I've set up the report and running it correctly?

Report 339  select itype,location,ccode,itemlost from items where barcode in (<<List Parameter>>)

Run Report 339, select list from the dropdown
Enter each barcode on its own line (barcodes exist in the catalog)
Click Run Report- no results displayed, just a blank screen

**Comment by kidclamp** [comment]
Plugin updated, previously we were adding '()' in the script, so with syntax suggested it was doubling and causing an error

Execution errors should be passed through now as well so you don't get a blank screen.
