### ISSUE TITLE
Parameters sent in URL, limiting the number of rows passed in

### ISSUE THREAD

**Issue by bartonski** [bywatersolutions/koha-reports-plus#6]
In the 'Fill in the params' section of the plugin, I paste in the values

    1111
    2222
    3333
    4444

Clicking `Run Report` yields the following URL:

https://example.com/cgi-bin/koha/plugins/run.pl?class=Koha%3A%3APlugin%3A%3ACom%3A%3AByWaterSolutions%3A%3AReportPlus&method=report&report_id=78&next=4&param_count=1&output=screen&param0.type=textarea&param0=1111%0D%0A2222%0D%0A3333%0D%0A4444

The values 1111, 2222, 3333 and 4444 appear in the URL

The maximum length of a URL is 2,083 characters, per https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

Assuming that the parameters are around 10 characters long and assuming that the without the parameters is about 200 characters long, this means that we can only paste  around 200 values into the 'Values' box before we get a 400 error due to an over-long URL.

Changing the form method in `report-step3.tt` from `get` to `post` fixes the problem.

**Comment by kidclamp** [comment]
Done
